.PHONY: clean All

All:
	@echo "----------Building project:[ Gioco - Debug ]----------"
	@"$(MAKE)" -f  "Gioco.mk"
clean:
	@echo "----------Cleaning project:[ Gioco - Debug ]----------"
	@"$(MAKE)" -f  "Gioco.mk" clean
